const songs = [
    {
        title: 'La isla bonita',
        artist: 'Madonna',
        image: require('../assets/artwork/1.png'),
        artwork: require('../assets/artwork/1.png'),
        url: require('../assets/songs/01_Morning_Dew.wav'),
        id: '1',
    },
    {
        title: 'The Trooper',
        artist: 'Iron Maiden',
        image: require('../assets/artwork/2.png'),
        artwork: require('../assets/artwork/2.png'),
        url: require('../assets/songs/02_Serenity.wav'),
        id: '2',
    },
    {
        title: 'American Idiot',
        artist: 'Green Day',
        image: require('../assets/artwork/3.png'),
        artwork: require('../assets/artwork/3.png'),
        url: require('../assets/songs/03_Petrichor.wav'),
        id: '3',
    },
    {
        title: 'Bohemian Rhapsody',
        artist: 'Queen',
        image: require('../assets/artwork/4.png'),
        artwork: require('../assets/artwork/4.png'),
        url: require('../assets/songs/04_Enchanting_Table.wav'),
        id: '4',
    },
    {
        title: 'Don\'t Start Now',
        artist: 'Dua Lipa',
        image: require('../assets/artwork/5.png'),
        artwork: require('../assets/artwork/5.png'),
        url: require('../assets/songs/05_Blankets.wav'),
        id: '5',
    },
    {
        title: 'mountain-path.mp3',
        artist: 'pixabay1',
        image: require('../assets/artwork/1.png'),
        artwork: require('../assets/artwork/1.png'),
        url: require('../assets/songs/06-mountain-path.mp3'),
        id: '6',
    },
    {
        title: '07-peaceful-garden.mp3',
        artist: 'pixabay2',
        image: require('../assets/artwork/2.png'),
        artwork: require('../assets/artwork/2.png'),
        url: require('../assets/songs/07-peaceful-garden.mp3'),
        id: '7',
    },
    {
        title: '08-please-calm-my-mind.mp3',
        artist: 'pixabay3',
        image: require('../assets/artwork/3.png'),
        artwork: require('../assets/artwork/3.png'),
        url: require('../assets/songs/08-please-calm-my-mind.mp3'),
        id: '8',
    },
    {
        title: '09-sedative.mp3',
        artist: 'pixabay4',
        image: require('../assets/artwork/4.png'),
        artwork: require('../assets/artwork/4.png'),
        url: require('../assets/songs/09-sedative.mp3'),
        id: '9',
    },
    {
        title: '10-emotional-cinematic.mp3',
        artist: 'pixabay5',
        image: require('../assets/artwork/5.png'),
        artwork: require('../assets/artwork/5.png'),
        url: require('../assets/songs/10-emotional-cinematic.mp3'),
        id: '10',
    },
]

export default songs;