// Generated by https://quicktype.io

export interface PlayerModel {
    _duration: number;
    _lastSync: number;
    _looping:  boolean;
    _options:  Options;
    _pan:      number;
    _path:     string;
    _playerId: number;
    _position: number;
    _speed:    number;
    _state:    number;
    _volume:   number;
    _wakeLock: boolean;
}

export interface Options {
    autoDestroy:                 boolean;
    category:                    number;
    continuesToPlayInBackground: boolean;
    mixWithOthers:               boolean;
}
